# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Forward port 8888 for Jupyter notebook
  config.vm.network "forwarded_port", guest: 8888, host: 8888

  # Forward port 6006 for TensorBoard
  config.vm.network "forwarded_port", guest: 6006, host: 6006

  config.vm.provider "virtualbox" do |vb|
    vb.name = "TensorFlow"
	vb.gui = true
	vb.memory = 2048
  end

  # Download and install everything on first run
  config.vm.provision "shell", path: "config.sh"
end