# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder "htdocs", "/var/www/html"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Monodevelop"
    vb.gui = true
  end

  # Download and install everything on first run
  config.vm.provision "shell", path: "config.sh"
end
